name: stonescrissorpaper
description: "A game with stone, scrissor and paper!"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  ionicons: ^0.2.2
  provider: ^6.1.2
  pull_down_button: ^0.10.2
  appbar_animated: ^0.0.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  lucide_icons_flutter: ^2.0.1

flutter:

  assets:
    - assets/images/Scissor.png
    - assets/images/Paper.png
    - assets/images/Stone.png

  uses-material-design: true
